[model]
name = "CATS"

[model.params]
enc_in = 8
patch_len = 24
d_model = 128
n_heads = 16
d_ff = 256
n_layers = 3
dropout = 0.1
stride = 24
attn_dropout = 0.0
query_independence = false
store_attn = false
QAM_start = 0.1
QAM_end = 0.5
